DROP TABLE CUSTOMER IF EXISTS ;

CREATE TABLE CUSTOMER (
  ID BIGINT GENERATED ALWAYS AS IDENTITY,
  FIRST_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  CREATION_TIME TIMESTAMP,
  LAST_MODIFIED_DATE TIMESTAMP,
  VERSION BIGINT,

  PRIMARY KEY (ID)
)
